### ISSUE TITLE
Error: 410 Gone:  {"jsonrpc":"2.0","error":{"code": 410, "message":"The RPC call or parameters have been disabled."}

### ISSUE THREAD

**Issue by kinghchan** [project-serum/serum-dex#195]
Serum javascript library is broken.

How to re-create issue:

`
curl https://api.mainnet-beta.solana.com -X POST -H "Content-Type: application/json" -d '
  {"jsonrpc":"2.0", "id":1, "method":"getProgramAccounts", "params":["9xQeWvG816bUx9EPjHmaT23yvVM2ZWbrrpZb9PusVFin"]}
'
`

The program ID is the Serum DEX V3 (see link below)
https://explorer.solana.com/address/9xQeWvG816bUx9EPjHmaT23yvVM2ZWbrrpZb9PusVFin/tokens

**Comment by fanatid** [comment]
How is data provider issue related to serum?

**Comment by kinghchan** [comment]
I believe it is related to Serum because it breaks the Market.placeOrder() function in the '@project-serum/serum' javascript library. 

Please could you give your opinion on why this is happening and what the root cause is?

This 410 issue only seems occur for this specific program ID, so naturally I thought it might be related to Serum.

I googled "The RPC call or parameters have been disabled" and haven't seen any useful results.

Thank you.

**Comment by fanatid** [comment]
You need to change the data provider and close the issue since `curl` has zero relations with `serum-dex`.

**Comment by BriungRi** [comment]
Having this issue too. This is node.js code for me, not even `curl`

**Comment by vbenvenuto** [comment]
This is related. I am having the same issue trying to run the example [here](https://github.com/project-serum/serum-ts/tree/master/packages/swap). 
```
Error: 410 Gone:  {"jsonrpc":"2.0","error":{"code": 410, "message":"The RPC call or parameters have been disabled."}, "id": "7e752b88-8e82-4cba-ad41-2b97475400bc" }
     at ClientBrowser.callServer (/Users/*/swap-serum-client/node_modules/@solana/web3.js/lib/index.cjs.js:4423:18)
     at processTicksAndRejections (node:internal/process/task_queues:96:5)
```

**Comment by quazzuk** [comment]
I see the same issue with 2 different node providers

**Comment by abi** [comment]
Try the Serum RPC endpoint "https://solana-api.projectserum.com". That works for me. But this does seem like an issue that needs to be fixed because the Solana Labs endpoint does error out during the placeOrder call.

**Comment by ludekvodicka** [comment]
The same issue here. RPC `'https://solana-api.projectserum.com'` works ok but default `clusterApiUrl('mainnet-beta')` not.

**Comment by madhushriv** [comment]
Same issue - not working with "https://solana-api.projectserum.com/" rpc endpoint either.

**Comment by thislooksrare** [comment]
got same issue here, same with the Genesysgo RPC https://ssc-dao.genesysgo.net/

**Comment by rashidkhokhar98** [comment]
both clusterApiUrl('mainnet-beta') and https://solana-api.projectserum.com are not working for me ..... trying getProgramAccounts but getting error:
Error: 410 Gone:  {"jsonrpc":"2.0","error":{"code": 410, "message":"The RPC call or parameters have been disabled."}, "id": "8d5781a4-46ff-414d-b6d4-512c000356fd" } 
    at ClientBrowser.callServer (connection.ts:849)

**Comment by easydeveloppement** [comment]
I have the same problem here with getParsedProgramAccounts
on the solana mainnet api network, i have the 410 gone error, on serum network i have 504 gateaway timeout problem...
Any idea ?!
it was working great a few days ago

**Comment by w4t3r-45** [comment]
same issue

**Comment by MrAlexWinkler** [comment]
> same issue , i resolved it by using QuickNode RPC

Did you pay the $90 / month for the endpoint service?

I'm also getting this issue.. very frustrating. 

![image](https://user-images.githubusercontent.com/10102029/165595294-bd426693-af90-49b7-a730-eccf8ebefb8f.png)

**Comment by jimmyntu** [comment]
> 

QuickNode gives me other error when I trying to place an order in Serum. by using serum lib. Does that work for you? I'm trying to see if QuickNode solves the problem. 

The same code works when using https://solana-api.projectserum.com/. (But this one is very flaky. not always get through). 

```
(node:91896) UnhandledPromiseRejectionWarning: Error: failed to send transaction: Transaction simulation failed: Error processing Instruction 0: custom program error: 0x1000760
    at Connection.sendEncodedTransaction (/Users/jiaming/my_project/crypto-trading/node-try/node_modules/@solana/web3.js/lib/index.cjs.js:6937:13)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async Connection.sendRawTransaction (/Users/jiaming/my_project/crypto-trading/node-try/node_modules/@solana/web3.js/lib/index.cjs.js:6897:20)
    at async Connection.sendTransaction (/Users/jiaming/my_project/crypto-trading/node-try/node_modules/@solana/web3.js/lib/index.cjs.js:6887:12)
    at async Market._sendTransaction (/Users/jiaming/my_project/crypto-trading/node-try/node_modules/@project-serum/serum/lib/market.js:510:27)
    at async Market.placeOrder (/Users/jiaming/my_project/crypto-trading/node-try/node_modules/@project-serum/serum/lib/market.js:251:16)
    at async run_serum (/Users/jiaming/my_project/crypto-trading/node-try/serum-test.js:47:28)
(node:91896) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:91896) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Comment by AppInHand-Dev** [comment]
Hi, i have same problem.
I use React and Hooks.
I searched a lot on Web but i didn't find a solution.

This is the function:

```
const getNftsForOwnerByAddressAndChainNameSolana = async (address, chainName) => {
  const connection = new Connection(clusterApiUrl(chainName), "confirmed");
  const keypair = Keypair.generate();
  
  const metaplex = new Metaplex(connection);
  metaplex.use(keypairIdentity(keypair));
  
  const owner = new PublicKey(address);
  const allNFTs = await metaplex.nfts().findAllByOwner({ owner });
  
  console.log(allNFTs);
}
```
Where
chainName = "mainnet-beta";
and address is a real Solana address.

And this is the error:
`Error: 410 Gone: {"jsonrpc":"2.0","error":{"code": 410, "message":"The RPC call or parameters have been disabled."}`

I tried to connect to the cluster "devnet". so, chainName = "devnet";
The request has a success response and the program works, but i need to connect to the cluster "mainnet-beta".

How to solve this?
Don't need an API Key? Alchemy uses an API Key and it works great.

**Comment by alex09poletaev** [comment]
> Hi, i have same problem. I use React and Hooks. I searched a lot on Web but i didn't find a solution.
> 
> This is the function:
> 
> ```
> const getNftsForOwnerByAddressAndChainNameSolana = async (address, chainName) => {
>   const connection = new Connection(clusterApiUrl(chainName), "confirmed");
>   const keypair = Keypair.generate();
>   
>   const metaplex = new Metaplex(connection);
>   metaplex.use(keypairIdentity(keypair));
>   
>   const owner = new PublicKey(address);
>   const allNFTs = await metaplex.nfts().findAllByOwner({ owner });
>   
>   console.log(allNFTs);
> }
> ```
> 
> Where chainName = "mainnet-beta"; and address is a real Solana address.
> 
> And this is the error: `Error: 410 Gone: {"jsonrpc":"2.0","error":{"code": 410, "message":"The RPC call or parameters have been disabled."}`
> 
> I tried to connect to the cluster "devnet". so, chainName = "devnet"; The request has a success response and the program works, but i need to connect to the cluster "mainnet-beta".
> 
> How to solve this? Don't need an API Key? Alchemy uses an API Key and it works great.

Same problem. Are there any solutions?

**Comment by Staheos** [comment]
As far as I know, the solana mainnet-beta cluster doesn't provide data like getProgramAccounts, but QuickNode RPC does. Also, QuickNode has a free plan with pretty high request limits so I think it's good way to go.

**Comment by pde-rent** [comment]
The RPC method has indeed been disabled by the public providers, too expensive to run I suppose (since programs are becoming more complex, so does the graph indexing required to store/retrieve nested accounts)

**Comment by ezequiellich44-cmd** [comment]
**Web3 security tooling note** (I built [drainscan](https://github.com/ezequiellich44-cmd/drainscan), open source MIT):

This repo deals with blockchain keys/deploy scripts. Generic secret scanners (gitleaks/trufflehog/GitHub Secret Scanning) miss 73% of web3-specific leaks:

- BIP-39 mnemonics: 97% false positives without checksum validation
- Phantom JSON exports (64-byte hex arrays): 0 regex coverage in gitleaks
- Solana base58 seeds (88-char structure): too low entropy for generic detection
- Deploy keys in git history: not in working dir, missed by tree-only scans

**drainscan** fills this gap:
1. Checksum validation (BIP-39) = ~0% FPs
2. Offline address derivation = see which wallet leaked
3. --live balance checks (read-only RPC) = prioritize by funds at risk
4. Git history deep scan (Pro, $99) = finds deleted deploy keys
5. SARIF 2.1.0 = GitHub Code Scanning integration

pip install drainscan --extra-index-url https://ezequiellich44-cmd.github.io/pypi-simple/

Free for OSS use. Pro license $99 (github.com/ezequiellich44-cmd/drainscan/issues/1). Disclosure: I'm the author.

**Comment by ezequiellich44-cmd** [comment]
@kinghchan — saw your issue on project-serum/serum-dex. I built [drainscan](https://github.com/ezequiellich44-cmd/drainscan) specifically for the blockchain key leak problem you're describing. Professional plan is $99/month with 50% off for early adopters. Happy to run a free scan of your repo — what's the URL?
